const codes = `AF AL DZ AD AO AG AR AM AU AT AZ BS BH BD BB BY BE BZ BJ BT BO BA BW BR BN BG BF BI CV KH CM CA CF TD CL CN CO KM CG CD CR CI HR CU CY CZ DK DJ DM DO EC EG SV GQ ER EE SZ ET FJ FI FR GA GM GE DE GH GR GD GT GN GW GY HT HN HU IS IN ID IR IQ IE IL IT JM JP JO KZ KE KI KP KR KW KG LA LV LB LS LR LY LI LT LU MG MW MY MV ML MT MH MR MU MX FM MD MC MN ME MA MZ MM NA NR NP NL NZ NI NE NG MK NO OM PK PW PA PG PY PE PH PL PT QA RO RU RW KN LC VC WS SM ST SA SN RS SC SL SG SK SI SB SO ZA SS ES LK SD SR SE CH SY TJ TZ TH TL TG TO TT TN TR TM TV UG UA AE GB US UY UZ VU VA VE VN YE ZM ZW PS`.split(' ');
const regionCodes={
  AFRICA:`DZ AO BJ BW BF BI CV CM CF TD KM CG CD CI DJ EG GQ ER SZ ET GA GM GH GN GW KE LS LR LY MG MW ML MR MU MA MZ NA NE NG RW ST SN SC SL SO ZA SS SD TZ TG TN UG ZM ZW`.split(' '),
  EUROPE:`AL AD AT BY BE BA BG HR CY CZ DK EE FI FR DE GR VA HU IS IE IT LV LI LT LU MT MD MC ME NL MK NO PL PT RO RU SM RS SK SI ES SE CH UA GB`.split(' '),
  ASIA:`AF AM AZ BH BD BT BN KH CN GE IN ID IR IQ IL JP JO KZ KW KG LA LB MY MV MN MM NP KP KR OM PK PS PH QA SA SG LK SY TJ TH TL TR TM AE UZ VN YE`.split(' '),
  AMERICAS:`AG AR BS BB BZ BO BR CA CL CO CR CU DM DO EC SV GD GT GY HT HN JM MX NI PA PY PE KN LC VC SR TT US UY VE`.split(' '),
  OCEANIA:`AU FJ KI MH FM NR NZ PW PG WS SB TO TV VU`.split(' ')
};
const regions=Object.fromEntries(Object.entries(regionCodes).flatMap(([r,cs])=>cs.map(c=>[c,r])));
const names=new Intl.DisplayNames(['en'],{type:'region'});
const countries=codes.map(code=>({code,name:names.of(code),region:regions[code]||'WORLD'}));
const levels={easy:{count:20,lives:5,multiplier:1,label:'Easy Explorer'},medium:{count:50,lives:4,multiplier:1.25,label:'Globe Trotter'},hard:{count:100,lives:3,multiplier:1.5,label:'Flag Expert'},master:{count:195,lives:3,multiplier:2,label:'World Master'}};
const $=id=>document.getElementById(id);
const screens=['homeScreen','gameScreen','resultScreen'];
let deck=[],round=0,score=0,lives=5,streak=0,bestStreak=0,correct=0,locked=false,hintUsed=false,soundOn=true,selectedLevel='easy';
const best=()=>Number(localStorage.getItem('atlas-best')||0);
function flagUrl(code){return `https://flagcdn.com/w320/${code.toLowerCase()}.png`}
function shuffle(a){for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function show(id){screens.forEach(s=>$(s).classList.toggle('active',s===id));window.scrollTo(0,0)}
function beep(good){if(!soundOn)return;const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const ctx=new C(),o=ctx.createOscillator(),g=ctx.createGain();o.connect(g);g.connect(ctx.destination);o.frequency.value=good?660:180;g.gain.setValueAtTime(.08,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.18);o.start();o.stop(ctx.currentTime+.18)}
function start(){const level=levels[selectedLevel];deck=shuffle([...countries]).slice(0,level.count);round=score=streak=bestStreak=correct=0;lives=level.lives;show('gameScreen');next()}
function next(){if(lives<=0||round>=deck.length){finish();return}locked=false;hintUsed=false;$('hintButton').disabled=false;const country=deck[round];$('score').textContent=score;$('roundLabel').textContent=`${round+1} / ${deck.length}`;$('progressBar').style.width=`${round/deck.length*100}%`;$('lives').textContent='♥ '.repeat(lives).trim();$('streak').textContent=streak;$('regionTag').textContent=country.region;$('flag').src=flagUrl(country.code);$('flag').alt=`Flag of ${country.name}`;
  const sameRegion=countries.filter(c=>c.code!==country.code&&c.region===country.region);const allOthers=countries.filter(c=>c.code!==country.code);const pool=selectedLevel==='easy'?allOthers.filter(c=>c.region!==country.region):[...sameRegion,...shuffle(allOthers)];const wrong=shuffle(pool).slice(0,3);const options=shuffle([country,...wrong]);$('answers').innerHTML='';options.forEach((c,i)=>{const b=document.createElement('button');b.className='answer';b.dataset.code=c.code;b.innerHTML=`<span class="letter">${'ABCD'[i]}</span><span>${c.name}</span>`;b.onclick=()=>answer(b,c.code===country.code,country);$('answers').appendChild(b)})}
function answer(button,isCorrect,country){if(locked)return;locked=true;const buttons=[...document.querySelectorAll('.answer')];buttons.forEach(b=>b.disabled=true);if(isCorrect){button.classList.add('correct');score+=Math.round((100+streak*10)*levels[selectedLevel].multiplier);streak++;correct++;bestStreak=Math.max(bestStreak,streak);beep(true)}else{button.classList.add('wrong');buttons.find(b=>b.dataset.code===country.code).classList.add('correct');lives--;streak=0;beep(false)}$('score').textContent=score;$('streak').textContent=streak;$('lives').textContent='♥ '.repeat(lives).trim();round++;setTimeout(next,950)}
function useHint(){if(locked||hintUsed)return;hintUsed=true;$('hintButton').disabled=true;const correct=deck[round].code;const wrong=shuffle([...document.querySelectorAll('.answer')].filter(b=>b.dataset.code!==correct)).slice(0,2);wrong.forEach(b=>{b.classList.add('hidden-choice');b.disabled=true});toast('Two wrong answers removed')}
function finish(){const oldBest=best(),isBest=score>oldBest,outOfLives=lives<=0,level=levels[selectedLevel];if(isBest)localStorage.setItem('atlas-best',score);$('bestScore').textContent=Math.max(oldBest,score);$('finalScore').textContent=score.toLocaleString();$('correctCount').textContent=correct;$('bestStreak').textContent=bestStreak;$('newBest').style.display=isBest?'block':'none';$('resultEyebrow').textContent=outOfLives?'GAME OVER':'LEVEL COMPLETE';$('resultTitle').textContent=outOfLives?'Out of hearts!':correct===deck.length?'Perfect journey!':'Journey complete!';$('resultMessage').textContent=outOfLives?`You used all ${level.lives} hearts and scored ${score.toLocaleString()} points with ${correct} correct.`:`You completed ${level.label} with ${correct} correct and ${score.toLocaleString()} points.`;show('resultScreen')}
let toastTimer;function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),1800)}
document.querySelectorAll('.level-card').forEach(card=>card.onclick=()=>{selectedLevel=card.dataset.level;document.querySelectorAll('.level-card').forEach(c=>c.classList.toggle('selected',c===card));$('playButton').childNodes[0].textContent=`Play ${levels[selectedLevel].label} `});
$('bestScore').textContent=best();$('playButton').onclick=start;$('againButton').onclick=start;$('hintButton').onclick=useHint;$('homeButton').onclick=()=>show('homeScreen');$('resultHomeButton').onclick=()=>show('homeScreen');$('soundButton').onclick=()=>{soundOn=!soundOn;$('soundButton').textContent=soundOn?'♪':'×';toast(soundOn?'Sound on':'Sound off')};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
