const codes = `AF AL DZ AD AO AG AR AM AU AT AZ BS BH BD BB BY BE BZ BJ BT BO BA BW BR BN BG BF BI CV KH CM CA CF TD CL CN CO KM CG CD CR CI HR CU CY CZ DK DJ DM DO EC EG SV GQ ER EE SZ ET FJ FI FR GA GM GE DE GH GR GD GT GN GW GY HT HN HU IS IN ID IR IQ IE IL IT JM JP JO KZ KE KI KP KR KW KG LA LV LB LS LR LY LI LT LU MG MW MY MV ML MT MH MR MU MX FM MD MC MN ME MA MZ MM NA NR NP NL NZ NI NE NG MK NO OM PK PW PA PG PY PE PH PL PT QA RO RU RW KN LC VC WS SM ST SA SN RS SC SL SG SK SI SB SO ZA SS ES LK SD SR SE CH SY TJ TZ TH TL TG TO TT TN TR TM TV UG UA AE GB US UY UZ VU VA VE VN YE ZM ZW PS`.split(' ');
const regionCodes={
  AFRICA:`DZ AO BJ BW BF BI CV CM CF TD KM CG CD CI DJ EG GQ ER SZ ET GA GM GH GN GW KE LS LR LY MG MW ML MR MU MA MZ NA NE NG RW ST SN SC SL SO ZA SS SD TZ TG TN UG ZM ZW`.split(' '),
  EUROPE:`AL AD AT BY BE BA BG HR CY CZ DK EE FI FR DE GR VA HU IS IE IT LV LI LT LU MT MD MC ME NL MK NO PL PT RO RU SM RS SK SI ES SE CH UA GB`.split(' '),
  ASIA:`AF AM AZ BH BD BT BN KH CN GE IN ID IR IQ IL JP JO KZ KW KG LA LB MY MV MN MM NP KP KR OM PK PS PH QA SA SG LK SY TJ TH TL TR TM AE UZ VN YE`.split(' '),
  AMERICAS:`AG AR BS BB BZ BO BR CA CL CO CR CU DM DO EC SV GD GT GY HT HN JM MX NI PA PY PE KN LC VC SR TT US UY VE`.split(' '),
  OCEANIA:`AU FJ KI MH FM NR NZ PW PG WS SB TO TV VU`.split(' ')
};
const regions=Object.fromEntries(Object.entries(regionCodes).flatMap(([r,cs])=>cs.map(c=>[c,r])));
const names=new Intl.DisplayNames(['en'],{type:'region'});
const countries=codes.map(code=>({code,name:names.of(code),region:regions[code]||'WORLD'}));
const levels={easy:{lives:5,multiplier:1,heartEvery:5,label:'Easy Explorer'},medium:{lives:4,multiplier:1.25,heartEvery:7,label:'Globe Trotter'},hard:{lives:3,multiplier:1.5,heartEvery:10,label:'Flag Expert'},master:{lives:3,multiplier:2,heartEvery:12,label:'World Master'}};
const $=id=>document.getElementById(id);
const screens=['homeScreen','gameScreen','resultScreen'];
let deck=[],round=0,score=0,lives=5,streak=0,bestStreak=0,correct=0,locked=false,hintUsed=false,soundOn=true,selectedLevel='easy';
const best=()=>Number(localStorage.getItem('atlas-best')||0);
const praise=['Sharp eye!','Excellent read!','Great instincts!','Beautifully played!'];
const recovery=['Stay focused — the next flag is yours.','Reset and rebuild. You’ve got this.','Every expert misses one. Keep exploring.','Don’t give up — a new streak starts now.'];
let audioCtx=null,musicTimer=null,musicStep=0;
function records(){try{return JSON.parse(localStorage.getItem('atlas-records')||'[]')}catch{return[]}}
function saveRecord(){if(score<=0)return 0;const entry={score,level:selectedLevel,streak:bestStreak,correct,date:new Date().toISOString()};const list=[...records(),entry].sort((a,b)=>b.score-a.score).slice(0,5);localStorage.setItem('atlas-records',JSON.stringify(list));return list.indexOf(entry)+1}
function renderRecords(){const list=records();$('recordList').innerHTML=list.length?list.map((r,i)=>`<li><span>#${i+1}</span><span>${levels[r.level]?.label||'Explorer'}<small>${r.correct} correct · ${r.streak} best streak</small></span><strong>${r.score.toLocaleString()}</strong></li>`).join(''):'<li class="leaderboard-empty">Play a game to set the first record!</li>'}
function flagUrl(code){return `https://flagcdn.com/w320/${code.toLowerCase()}.png`}
function shuffle(a){for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function show(id){if(id!=='gameScreen')stopMusic();screens.forEach(s=>$(s).classList.toggle('active',s===id));window.scrollTo(0,0)}
function ensureAudio(){if(!soundOn)return null;const C=window.AudioContext||window.webkitAudioContext;if(!C)return null;if(!audioCtx)audioCtx=new C();if(audioCtx.state==='suspended')audioCtx.resume();return audioCtx}
function tone(frequency,duration=.16,type='sine',volume=.04,delay=0){const ctx=ensureAudio();if(!ctx)return;const o=ctx.createOscillator(),g=ctx.createGain(),at=ctx.currentTime+delay;o.type=type;o.frequency.setValueAtTime(frequency,at);g.gain.setValueAtTime(volume,at);g.gain.exponentialRampToValueAtTime(.001,at+duration);o.connect(g);g.connect(ctx.destination);o.start(at);o.stop(at+duration)}
function beep(good){if(good){tone(523,.16,'sine',.05);tone(659,.2,'sine',.04,.08)}else{tone(220,.2,'triangle',.045);tone(165,.25,'triangle',.035,.1)}}
function startMusic(){stopMusic();if(!soundOn)return;ensureAudio();const melody=[261.63,329.63,392,329.63,293.66,349.23,440,349.23,246.94,293.66,392,293.66];musicStep=0;const play=()=>{if(!soundOn)return;const note=melody[musicStep%melody.length];tone(note,.42,'triangle',.012);if(musicStep%4===0)tone(note/2,.55,'sine',.009);musicStep++};play();musicTimer=setInterval(play,620)}
function stopMusic(){if(musicTimer){clearInterval(musicTimer);musicTimer=null}}
function fanfare(){[523,659,784,1047].forEach((n,i)=>tone(n,.35,'sine',.055,i*.12))}
function setCoach(message,type='positive'){$('coachMessage').textContent=message;$('coachMessage').className=`coach-message ${type}`}
function praiseForStreak(value){if(value>=20)return'Legendary run — world-class focus!';if(value>=12)return'Unstoppable! Your streak is soaring.';if(value>=7)return'On fire — keep the momentum alive!';if(value>=3)return'Momentum building — keep going!';return praise[Math.floor(Math.random()*praise.length)]}
function start(){const level=levels[selectedLevel];ensureAudio();deck=shuffle([...countries]);round=score=streak=bestStreak=correct=0;lives=level.lives;$('heartGoal').textContent=`+♥ AT ${level.heartEvery}`;setCoach('Your world tour starts now. Build that streak!');show('gameScreen');startMusic();next()}
function next(){if(lives<=0){finish();return}if(round>0&&round%countries.length===0)deck=shuffle([...countries]);locked=false;hintUsed=false;$('hintButton').disabled=false;const country=deck[round%countries.length];$('score').textContent=score;$('roundLabel').textContent=`FLAG #${round+1}`;$('progressBar').style.width=`${((round%countries.length)+1)/countries.length*100}%`;$('lives').textContent='♥ '.repeat(lives).trim();$('lives').setAttribute('aria-label',`${lives} hearts remaining`);$('streak').textContent=streak;$('regionTag').textContent=country.region;$('flag').src=flagUrl(country.code);$('flag').alt=`Flag of ${country.name}`;
  const sameRegion=countries.filter(c=>c.code!==country.code&&c.region===country.region),allOthers=countries.filter(c=>c.code!==country.code);const pool=selectedLevel==='easy'?allOthers.filter(c=>c.region!==country.region):selectedLevel==='medium'?allOthers:sameRegion;const wrong=shuffle([...pool]).slice(0,3);const options=shuffle([country,...wrong]);$('answers').innerHTML='';options.forEach((c,i)=>{const b=document.createElement('button');b.className='answer';b.dataset.code=c.code;b.innerHTML=`<span class="letter">${'ABCD'[i]}</span><span>${c.name}</span>`;b.onclick=()=>answer(b,c.code===country.code,country);$('answers').appendChild(b)})}
function answer(button,isCorrect,country){if(locked)return;locked=true;const level=levels[selectedLevel],buttons=[...document.querySelectorAll('.answer')];buttons.forEach(b=>b.disabled=true);if(isCorrect){button.classList.add('correct');streak++;correct++;let earned=Math.round((100+Math.max(0,streak-2)*25)*level.multiplier);if(hintUsed)earned=Math.round(earned*.7);const milestone=streak%level.heartEvery===0;if(milestone){earned+=Math.round(250*level.multiplier);if(lives<level.lives+2)lives++;setCoach(`Streak reward! Heart restored at ${streak} correct.`, 'positive');toast(`🔥 +♥ HEART · +${earned} POINTS`);fanfare()}else{setCoach(praiseForStreak(streak),'positive');toast(`+${earned} points · ${streak} streak`);beep(true)}score+=earned;bestStreak=Math.max(bestStreak,streak)}else{button.classList.add('wrong');buttons.find(b=>b.dataset.code===country.code).classList.add('correct');lives--;streak=0;setCoach(recovery[Math.floor(Math.random()*recovery.length)],'warning');toast(lives?`Heart lost · ${lives} remaining`:'Final heart lost · scoring your run');beep(false)}$('score').textContent=score;$('score').classList.add('score-pop');setTimeout(()=>$('score').classList.remove('score-pop'),350);$('streak').textContent=streak;$('lives').textContent='♥ '.repeat(lives).trim();round++;setTimeout(next,950)}
function useHint(){if(locked||hintUsed)return;hintUsed=true;$('hintButton').disabled=true;const correct=deck[round%countries.length].code;const wrong=shuffle([...document.querySelectorAll('.answer')].filter(b=>b.dataset.code!==correct)).slice(0,2);wrong.forEach(b=>{b.classList.add('hidden-choice');b.disabled=true});toast('50/50 used · 30% fewer points')}
function finish(){const oldBest=best(),isBest=score>oldBest,level=levels[selectedLevel];if(isBest)localStorage.setItem('atlas-best',score);const position=saveRecord();$('bestScore').textContent=Math.max(oldBest,score);$('finalScore').textContent=score.toLocaleString();$('correctCount').textContent=correct;$('bestStreak').textContent=bestStreak;$('newBest').style.display=isBest?'block':'none';$('resultEyebrow').textContent='RUN COMPLETE';$('resultTitle').textContent=isBest?'A new personal best!':'A strong world tour!';$('resultMessage').textContent=`${level.label}: ${correct} correct flags and a ${bestStreak}-answer best streak.`;$('recordPosition').style.display=position?'block':'none';$('recordPosition').textContent=position?`🏅 New local record: #${position} on this device`:'';renderRecords();show('resultScreen');fanfare()}
let toastTimer;function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),1800)}
document.querySelectorAll('.level-card').forEach(card=>card.onclick=()=>{selectedLevel=card.dataset.level;document.querySelectorAll('.level-card').forEach(c=>c.classList.toggle('selected',c===card));$('playButton').childNodes[0].textContent=`Play ${levels[selectedLevel].label} `});
$('bestScore').textContent=best();renderRecords();$('playButton').onclick=start;$('againButton').onclick=start;$('hintButton').onclick=useHint;$('homeButton').onclick=()=>{renderRecords();show('homeScreen')};$('resultHomeButton').onclick=()=>{renderRecords();show('homeScreen')};$('soundButton').onclick=()=>{soundOn=!soundOn;$('soundButton').textContent=soundOn?'♪':'×';$('soundButton').setAttribute('aria-label',soundOn?'Mute music and sounds':'Turn on music and sounds');if(soundOn&&$('gameScreen').classList.contains('active'))startMusic();else stopMusic();toast(soundOn?'Music and sound on':'Music and sound off')};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
